name: Build image upon PR for main branch
on:
  # Pull request event triggers on default when a new pr is created,
  # closed pr is reopened or a new commit is added to an open pr.
  pull_request:
    branches:
      - master
    paths:
      - 'test/*/Dockerfile'
      - 'test/*/image_files/**'
      
jobs:
  Build-docker-image:
    runs-on: ubuntu-20.04
    steps:
      # Echo github event name
      - name: github event
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
